# Generated by Django 4.0 on 2022-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_article_link_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=3000)),
                ('Caption', models.CharField(max_length=300)),
                ('Link', models.CharField(max_length=2500)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='Link',
            field=models.CharField(max_length=2500),
        ),
    ]
